# Give it a name
name: Test Jupyter Notebook

# Describe when it runs.
on:
  push:
  pull_request:

# Describe the "jobs" that happens when it runs, and the steps in each job.
jobs:

  # We just have one job - running and checking the notebook.
  test-notebook:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbval jupyter pytest
          pip install -r requirements.txt

      - name: Clean Jupyter notebook
        run: |
          jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace demo.ipynb

      # Run notebook tests
      - name: Run demo.ipynb with pytest-nbval
        run: |
          pytest --nbval-lax demo.ipynb
